dist: xenial
language: python
matrix:
  include:
    - python: 3.7
      arch: amd64
      env:
        - FLAKE8=true
        - CONDA_VERSION=release
      dist: xenial
    - python: 3.7
      arch: arm64
      env:
        - FLAKE8=true
        - CONDA_VERSION=release
      dist: xenial
    - python: 3.7
      arch: amd64
      env:
        - DOCS=true
        - CONDA_VERSION=release
      dist: xenial
    - python: 3.7
      arch: arm64
      env:
        - DOCS=true
        - CONDA_VERSION=release
      dist: xenial

addons:
  apt:
    packages:
    - attr
    - mercurial

before_install:
  - sudo apt-get install -y git wget libtiff-dev

env:
  global:
    - SUDO=""

install:
  # show which shell we are running
  - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
      wget -q "https://github.com/Archiconda/build-tools/releases/download/0.2.3/Archiconda3-0.2.3-Linux-aarch64.sh" -O archiconda.sh;
      chmod +x archiconda.sh;
      bash archiconda.sh -b -p /opt/conda;
      SUDO=sudo;
      $SUDO cp -r /opt/conda/bin/* /usr/bin/;
    else
      wget http://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p /opt/conda;
    fi
  - ps -ef | grep $$
  - source /opt/conda/bin/activate
  - conda update -y conda;
  - conda config --set always_yes yes
  - conda config --set auto_update_conda False
  - conda info
  # avoids a python 3.7 problem
  - conda install -q cytoolz
  - conda install -q anaconda-client requests filelock contextlib2 jinja2 patchelf ripgrep pyflakes beautifulsoup4 chardet pycrypto glob2 psutil pytz tqdm conda-package-handling py-lief python-libarchive-c
  - pip install pkginfo
  - if [[ "$FLAKE8" == "true" ]]; then
      conda install -q flake8;
    else
      pip install -r requirements-docs.txt;
    fi
  - pip install --no-deps .
  - conda info -a

script: ./ci/travis/run.sh

notifications:
    flowdock: ef3821a08a791106512ccfc04c92eccb

git:
  depth: 10000

